Добавлена архитектура и сервис статистики.
DobryakovRoman/java-explore-with-me pull request #3
Opened 2023-05-21 21:00 UTC by DobryakovRoman

2023-05-22 19:40 UTC, alexache requested changes

2023-05-22 19:40 UTC, alexache commented on pom.xml
> +	<dependencies>
Может это лучше в dependencyManagement? Зачем все эти зависимости всем модулям?

2023-05-22 19:40 UTC, alexache commented on stats/stats-client/pom.xml
> +            <version>2.7.5</version>
Версии должны быть указаны только в родительском модуле

2023-05-22 19:40 UTC, alexache commented on stats/stats-client/src/main/java/ru/practicum/StatsClient.java
> +    static final String URL = "http://stats-server:9090";
Не понадобится менять URI?

2023-05-22 19:40 UTC, alexache commented on stats/stats-server/src/main/java/ru/practicum/controller/StatsController.java
> +    EndpointHitDto addEndpointHit(@RequestBody EndpointHitDto endpointHitDto) {
Не хватает модификатора доступа метода, а для ДТО разве не нужна валидация?

2023-05-22 19:40 UTC, alexache commented on stats/stats-server/src/main/java/ru/practicum/model/EndpointHit.java
> +                && app.equals(thisHit.app)
У JPA моделей не стоит использовать все поля в equals/hashcode

2023-05-22 19:40 UTC, alexache commented on stats/stats-server/src/main/java/ru/practicum/service/DtoMapper.java
> +@FieldDefaults(level = AccessLevel.PRIVATE)
Для каких полей?

2023-05-22 19:40 UTC, alexache commented on stats/stats-server/src/main/java/ru/practicum/service/StatsServiceImpl.java
> +        if (endpointHitDto.getApp() == null || endpointHitDto.getApp().isEmpty()) {
Почему бы не валидировать аннотациями в ДТО?

2023-05-28 19:36 UTC, DobryakovRoman commented on stats/stats-server/src/main/java/ru/practicum/service/DtoMapper.java
> +@FieldDefaults(level = AccessLevel.PRIVATE)
Исправил.

2023-05-28 19:55 UTC, DobryakovRoman commented on stats/stats-server/src/main/java/ru/practicum/service/StatsServiceImpl.java
> +        if (endpointHitDto.getApp() == null || endpointHitDto.getApp().isEmpty()) {
Готово.

2023-05-28 20:05 UTC, DobryakovRoman commented on stats/stats-server/src/main/java/ru/practicum/model/EndpointHit.java
> +                && app.equals(thisHit.app)
Понял, я пока совсем удалю, IDEA генерит со всеми полями.

2023-05-28 20:33 UTC, DobryakovRoman commented on stats/stats-server/src/main/java/ru/practicum/controller/StatsController.java
> +    EndpointHitDto addEndpointHit(@RequestBody EndpointHitDto endpointHitDto) {
Поправил. Спасибо.

2023-05-28 21:19 UTC, DobryakovRoman commented on stats/stats-client/src/main/java/ru/practicum/StatsClient.java
> +    static final String URL = "http://stats-server:9090";
Ну, на диплом нет)
Его добавить через application.properties?

2023-05-30 20:17 UTC, DobryakovRoman commented on pom.xml
> +	<dependencies>
Сделал

2023-05-30 20:18 UTC, DobryakovRoman commented on stats/stats-client/pom.xml
> +            <version>2.7.5</version>
dependencyManagement разобрался вроде, теперь все версии в родительском pom

2023-05-30 20:19 UTC, DobryakovRoman commented on stats/stats-client/src/main/java/ru/practicum/StatsClient.java
> +    static final String URL = "http://stats-server:9090";
Переложил в application.properties

2023-05-31 18:30 UTC, alexache approved these changes

2023-05-31 18:31 UTC, alexache approved these changes

2023-05-31 20:47 UTC, merged