0.0.5 feat: Этап 2
DobryakovRoman/java-explore-with-me pull request #4
Opened 2023-06-08 20:30 UTC by DobryakovRoman

2023-06-12 20:30 UTC, alexache requested changes

2023-06-12 20:30 UTC, alexache commented on docker-compose.yml
> +      - db-ewm
Еще зависит от сервиса статистики

2023-06-12 20:30 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +        if (categoryRepository.findByName(newCategoryRequestDto.getName()).size() > 0) {
(опционально) лучше подходят методы репозитория, как existsByName()

2023-06-12 20:30 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +        List<Event> eventsByCat = eventRepository.findAllByCategoryId(catId);
(опционально) тоже можно бы через existsByCategoryId

2023-06-12 20:30 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +            if (!catId.equals(id)) {
А как это условие может выполниться, если выше был фильтр?

2023-06-12 20:30 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/compilation/repository/CompilationRepository.java
> +    @Query("SELECT c FROM Compilation c " +
Зачем такой просто запрос делать через @Query? Отчего бы не через именование метода? Такой же вопрос и к следующему методу

2023-06-12 20:30 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/compilation/service/CompilationDtoMapper.java
> +    private final EventDtoMapper eventDtoMapper = new EventDtoMapper();
Зачем делать работу за спринг? Несложно ведь получить требуемый бин через много разных способов инжекции

2023-06-12 20:30 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/compilation/service/CompilationServiceImpl.java
> +        List<Event> events = eventRepository.findEventsByIds(compilationDto.getEvents());
Может это внести в условие ниже: чтобы делать обращение к базе в случае наличия событий

2023-06-12 20:30 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/compilation/service/CompilationServiceImpl.java
> +        for (Compilation compilation : compilations) {
(опционально) почему бы не сделать это через стримы?

2023-06-12 20:30 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/event/dto/NewEventDto.java
> +    String eventDate;
Почему строкой?

2023-06-12 20:30 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/event/dto/UpdateEventAdminRequest.java
> +public class UpdateEventAdminRequest {
А чем содержимое отличается от UpdateEventUserRequest ?

2023-06-12 20:30 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/event/model/Event.java
> +    Long confirmedRequests;
Это не должно хранится в таблице событий: для этого есть таблица с заявками

2023-06-12 20:30 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/event/repository/EventRepository.java
> +    @Query("SELECT event FROM Event event " +
Тоже многие эти методы можно сделать без @Query

2023-06-12 20:30 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/event/service/EventDtoMapper.java
> +    final CategoryDtoMapper categoryDtoMapper = new CategoryDtoMapper();
Не нужно создавать объекты

2023-06-12 20:30 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/event/service/EventService.java
> +    EventFullDto getEventDtoById(Long eventId, HttpServletRequest request);
HttpServletRequest  выглядит странным для интерфейса сервиса: который может быть и не завязан на HTTP - лучше передавать конкретные поля

2023-06-12 20:30 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/request/dto/EventRequestStatusUpdateRequest.java
> +    String status;
Валидации не требуются?

2023-06-12 20:30 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/request/dto/EventRequestStatusUpdateResult.java
> +    public void addRequest(ParticipationRequest request) {
Как-то на вид слишком много логики для ДТО класса, часть которой может делать маппер или сам сервис

2023-06-12 20:30 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/request/model/ParticipationRequest.java
> +    Long requester;
Почему не объект таблицы пользователя?

2023-06-12 20:30 UTC, alexache commented on ewm-service/src/main/resources/schema.sql
> +CREATE TABLE locations
У многих таблиц потеряно IF NOT EXISTS

2023-06-12 20:30 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +        User user = userService.getUserById(userId);
Лучше работать напрямую с репозиториями: нежели добавлять зависимости между сервисами

2023-06-12 20:30 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +        return getViewsCounter(eventFullDto);
Какие могут быть просмотры на еще несозданном событии?

2023-06-12 20:30 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +//        if (categories == null) {
Закомментированного кода не должно быть

2023-06-12 20:30 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +        dtos = getViewCounters(dtos);
А где подсчет количества подтвержденных заявок на события?

2023-06-12 20:30 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +    void saveLocation(Event event) {
Приватные методы должны быть после публичных

2023-06-12 20:30 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +            String requestURI = request.getRequestURI();
Для чего эти 2 переменные?

2023-06-12 20:30 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +        }
А где использование разных видов сортировок?

2023-06-12 20:30 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +            eventIdsWithViewsCounter.put(event.getId(), getViewsCounter(eventDtoMapper.mapEventToFullDto(event)).getViews());
Не стоит делать запросы к сторонним сервисам (и базе) в цикле, Интерфейс позволяет делать это сразу для списка событий

2023-06-12 20:30 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +                    dto.setConfirmedRequests(dto.getConfirmedRequests() + 1);
Это очень странный способ, Можно в sql запросе сделать сразу и подсчет количества подтвержденных заявок на каждое событие

2023-06-12 20:30 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +            getViewsCounter(dto);
Это не должно вызываться в цикле

2023-06-12 20:30 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/request/service/RequestServiceImpl.java
> +                confirmedRequestsCounter += 1;
Подсчитывать бы можно уже запросом к базе

2023-06-12 20:30 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/request/service/RequestServiceImpl.java
> +                event.setConfirmedRequests(event.getConfirmedRequests() + 1);
А если это реджект? И почему вообще в базу записывать количество заявок

2023-06-12 20:30 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/request/service/RequestServiceImpl.java
> +            if (updateRequest.getRequestIds().contains(request.getId())) {
Какой-то странный квадратичный алгоритм, можно ведь просто менять статус по айди, а не сохранять объект целиком

2023-06-12 20:30 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/request/service/RequestServiceImpl.java
> +                event.setConfirmedRequests(event.getConfirmedRequests() + 1);
И что если мы теперь превысим лимит?

2023-06-13 16:51 UTC, DobryakovRoman commented on ewm-service/src/main/resources/schema.sql
> +CREATE TABLE locations
Исправил

2023-06-13 16:51 UTC, DobryakovRoman commented on docker-compose.yml
> +      - db-ewm
Исправил

2023-06-13 16:52 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/compilation/repository/CompilationRepository.java
> +    @Query("SELECT c FROM Compilation c " +
Исправил

2023-06-13 16:54 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/compilation/service/CompilationDtoMapper.java
> +    private final EventDtoMapper eventDtoMapper = new EventDtoMapper();
Исправил

2023-06-13 16:57 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/compilation/service/CompilationServiceImpl.java
> +        List<Event> events = eventRepository.findEventsByIds(compilationDto.getEvents());
Да, поправил.

2023-06-13 17:00 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/event/dto/UpdateEventAdminRequest.java
> +public class UpdateEventAdminRequest {
Они не отличаются, но оба должны быть по ТЗ.
![image](https://github.com/DobryakovRoman/java-explore-with-me/assets/25319074/7fec0b42-c7d6-4cd1-adf8-d5fd3221b48f)

2023-06-13 19:29 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/event/dto/NewEventDto.java
> +    String eventDate;
Сначала не обратил внимание, потом исправлял в маппере.
Исправил

2023-06-13 19:32 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +            if (!catId.equals(id)) {
Исправил.

2023-06-13 19:42 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/event/service/EventDtoMapper.java
> +    final CategoryDtoMapper categoryDtoMapper = new CategoryDtoMapper();
Исправил.

2023-06-13 19:51 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/request/dto/EventRequestStatusUpdateRequest.java
> +    String status;
Добавил.

2023-06-13 19:53 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +//        if (categories == null) {
Исправил.

2023-06-13 19:55 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +    void saveLocation(Event event) {
Исправил.

2023-06-13 19:56 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +            String requestURI = request.getRequestURI();
Удалил, они не нужны как и комментарии.

2023-06-13 20:06 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +            getViewsCounter(dto);
Исправил.

2023-06-13 20:35 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/event/model/Event.java
> +    Long confirmedRequests;
Удалил.

2023-06-13 21:24 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/event/repository/EventRepository.java
> +    @Query("SELECT event FROM Event event " +
Поправил. Прошу проверить.

2023-06-13 21:41 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/event/service/EventService.java
> +    EventFullDto getEventDtoById(Long eventId, HttpServletRequest request);
Исправил.

2023-06-13 22:14 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/request/dto/EventRequestStatusUpdateResult.java
> +    public void addRequest(ParticipationRequest request) {
Исправил. Поправил сервис и добавил маппер.

2023-06-13 22:28 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/request/model/ParticipationRequest.java
> +    Long requester;
На самом деле это связано с запросами, которые я написал в Repository. Сначала event и requester были Long, но потом я поменял event, чтобы запросы получилось написать.
Это надо исправить?

2023-06-13 22:41 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +        User user = userService.getUserById(userId);
Исправил.

2023-06-13 22:47 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +        return getViewsCounter(eventFullDto);
Да, исправил.

2023-06-13 22:55 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +        dtos = getViewCounters(dtos);
Я исправил, когда удалял это поле из модели Ивента. Исправил маппер и добавил ещё один метод.
    EventFullDto getEventFullDto(Event event) {
        Integer confirmed = requestRepository.findRequestByStatus("CONFIRMED").size();
        return EventDtoMapper.mapEventToFullDto(event, confirmed);
    }

2023-06-14 00:14 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +        }
Доделал.

2023-06-14 01:04 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +                    dto.setConfirmedRequests(dto.getConfirmedRequests() + 1);
Исправил.

2023-06-14 01:13 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/request/service/RequestServiceImpl.java
> +                confirmedRequestsCounter += 1;
Исправил.

2023-06-14 01:14 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/request/service/RequestServiceImpl.java
> +                event.setConfirmedRequests(event.getConfirmedRequests() + 1);
Исправил.

2023-06-14 01:34 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/request/service/RequestServiceImpl.java
> +            if (updateRequest.getRequestIds().contains(request.getId())) {
Исправил. Сначала я искал варианты как сравнить листы, поэтому цикл так и остался.

2023-06-14 04:04 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/request/service/RequestServiceImpl.java
> +                event.setConfirmedRequests(event.getConfirmedRequests() + 1);
Добавил логику, надо остальные реквесты реджектить.

2023-06-14 05:04 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +            eventIdsWithViewsCounter.put(event.getId(), getViewsCounter(eventDtoMapper.mapEventToFullDto(event)).getViews());
Переписал на получение списком. Прошу проверить.

2023-06-14 18:12 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/request/model/ParticipationRequest.java
> +    Long requester;
Лучше исправить

2023-06-14 18:41 UTC, alexache requested changes

2023-06-14 18:41 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/event/controller/EventController.java
> +    HttpServletRequest request;
Что это за поле  такое интересное появилось без модификатора доступа, откуда оно берется?

2023-06-14 18:41 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +        Integer confirmedRequests = requestRepository.findRequestByEventIdAndStatus(event.getId(), "CONFIRMED").size();
Если не нужны сами запросы,а только их количество, то оптимальнее будет использовать count* методы

2023-06-14 18:41 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +                .filter((event) -> EventState.PUBLISHED.equals(event.getState()))
А почему бы это не сделать частью запросов?

2023-06-14 18:41 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +            dto.setConfirmedRequests(requestRepository.countByEventAndStatuses(dto.getId(), List.of("CONFIRMED")));
Это запросы к базе в цикле, так нельзя делать, а для чего там выше запрашиваются requests?

2023-06-14 18:41 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +        return dtos.stream().map(this::getViewsCounter).collect(Collectors.toList());
Это тоже запросы к сервису статистики в цикле? Так тоже нельзя делать

2023-06-14 18:41 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/request/service/RequestServiceImpl.java
>                  requestRepository.save(request);
Это сохранение внутри цикла, лучше сделать после цикла saveAll на списке

2023-06-14 18:41 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/request/service/RequestServiceImpl.java
> +                    if (!checkForParticipantLimit(event)) {
Зачем на каждом шаге цикла обращаться к базе? Можно ведь 1 раз запросить до цикла, и считать, сколько еще заявок подтерждено, чтобы понять, когда уже можно реджектить

2023-06-15 18:24 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/event/controller/EventController.java
> +    HttpServletRequest request;
Добавил модификатор final.
Я его добавил, в связи с тем, что была просьба убрать из сервиса HttpServletRequest, и вместо него в параметры метода передавать поля. Поэтому я его вынес в контроллер и в методы getEventsWithFilters передаю строки с uri и ip адресом.

2023-06-15 18:35 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +        Integer confirmedRequests = requestRepository.findRequestByEventIdAndStatus(event.getId(), "CONFIRMED").size();
Исправил.

2023-06-15 19:10 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +                .filter((event) -> EventState.PUBLISHED.equals(event.getState()))
Добавил в запросы

2023-06-15 19:54 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +            dto.setConfirmedRequests(requestRepository.countByEventAndStatuses(dto.getId(), List.of("CONFIRMED")));
Исправил. Теперь 1 запрос, а данные заполняются в стриме.

2023-06-15 23:18 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +        return dtos.stream().map(this::getViewsCounter).collect(Collectors.toList());
Исправил.

2023-06-16 16:27 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/request/service/RequestServiceImpl.java
>                  requestRepository.save(request);
Исправил.

2023-06-16 18:44 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/request/service/RequestServiceImpl.java
> +                    if (!checkForParticipantLimit(event)) {
Исправил.

2023-06-16 20:46 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/request/model/ParticipationRequest.java
> +    Long requester;
Готово.

2023-06-16 21:40 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/compilation/service/CompilationServiceImpl.java
> +        for (Compilation compilation : compilations) {
Готово

2023-06-16 21:45 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +        List<Event> eventsByCat = eventRepository.findAllByCategoryId(catId);
Готово

2023-06-16 23:01 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +        if (categoryRepository.findByName(newCategoryRequestDto.getName()).size() > 0) {
Исправил

2023-06-17 06:40 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/event/controller/EventController.java
> +    HttpServletRequest request;
Да, просил убрать из интерфейса сервиса, но не контроллера, То есть пусть контроллер и дальше получает его на вход метода, но при вызове сервиса раскладывает на нужные свойства

2023-06-17 06:50 UTC, alexache approved these changes

2023-06-17 06:56 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/event/controller/EventController.java
> +    HttpServletRequest request;
Исправил.
Спасибо.

2023-06-17 07:21 UTC, merged