Этап 3: Комментарии
DobryakovRoman/java-explore-with-me pull request #5
Opened 2023-06-17 15:58 UTC by DobryakovRoman

2023-06-19 08:07 UTC, alexache requested changes

2023-06-19 08:07 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/comments/controller/CommentsController.java
> +    final CommentService commentService;
Не хватает модификатора доступа

2023-06-19 08:07 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/comments/dto/CommentDto.java
> +@Getter
Зачем и @Getter/@Setter и @Data?

2023-06-19 08:07 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/comments/dto/CommentDto.java
> +    String published;
Это даты? Почему они строками?

2023-06-19 08:07 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/comments/repository/CommentRepository.java
> +    @Query("SELECT comment FROM Comment comment " +
(опционально) Эти @Query достаточно легко переписать просто с использованием имени метода

2023-06-19 08:07 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/comments/service/CommentServiceImpl.java
> +        Comment comment = commentRepository.save(getCommentFromDto(userId, eventId, newCommentDto));
Может стоит еще проверять, что этот юзер действительно ходил на это событие, если считать это отзывом на поход?

2023-06-19 17:35 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/comments/controller/CommentsController.java
> +    final CommentService commentService;
Исправил.

2023-06-19 17:49 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/comments/dto/CommentDto.java
> +@Getter
Убрал @Data, подумал, что для DTO не требуется всего функционала, который добавляет @Data.

2023-06-19 17:50 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/comments/dto/CommentDto.java
> +    String published;
Исправил.

2023-06-19 18:03 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/comments/repository/CommentRepository.java
> +    @Query("SELECT comment FROM Comment comment " +
Теперь я разобрался как использовать поля другой таблицы)
Спасибо огромное)

2023-06-19 20:52 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/comments/service/CommentServiceImpl.java
> +        Comment comment = commentRepository.save(getCommentFromDto(userId, eventId, newCommentDto));
Добавил.
Теперь комментарий можно добавить только когда событие прошло, заявка пользователя была подтверждена и событие было опубликовано.

2023-06-19 21:00 UTC, DobryakovRoman commented
Спасибо, что ещё раз напомнил про запросные методы. Теперь понял, что можно обращаться к полям связанных таблиц, почему-то ранее я пропустил эту информацию.

2023-06-19 21:27 UTC, alexache approved these changes

2023-06-19 21:27 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/comments/service/CommentServiceImpl.java
> +        User user = userRepository.findById(userId).orElseThrow(
объект User уже был получен в методе выше, зачем повторно?

2023-06-20 19:39 UTC, DobryakovRoman commented on ewm-service/src/main/java/ru/practicum/comments/service/CommentServiceImpl.java
> +        User user = userRepository.findById(userId).orElseThrow(
Исправил.

2023-06-20 19:47 UTC, merged